A:
	g++ -Wall -o A.out A.cpp
	./A.out
	
B:
	g++ -Wall -o B.out B.cpp
	./B.out

C:
	g++ -Wall -o C.out C.cpp
	./C.out

D:
	g++ -Wall -o D.out D.cpp
	./D.out

G:
	g++ -Wall -o G.out G.cpp
	./G.out

H:
	g++ -Wall -o H.out H.cpp
	./H.out

I:
	g++ -Wall -o I.out I.cpp
	./I.out

J:
	g++ -Wall -o J.out J.cpp
	./J.out

L:
	g++ -Wall -o L.out L.cpp
	./L.out

M:
	g++ -Wall -o M.out M.cpp
	./M.out

is_prime:
	g++ -Wall -o is_prime.out is_prime.cpp
	./is_prime.out